; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[Purple]
button = B693CE
button-active = B693CE

[Summer_Sky]
button = e2a16c
button-active = e2a16c

[NyanCat]
button = EDA1DB
button-active = EDA1DB

[Stray]
button = e1b72d
button-active = e1b72d

 ; color.ini

 ; ... other themes

 [FPE]
 ; each field should be six digits hex colors without # (e.g. b693ce)
 button = f8f8ff ; color of the buttons in the app
 button-active = f8f8ff ; kinda the same
